### ISSUE TITLE
Usage with 2FA enabled

### ISSUE THREAD

**Issue by ManuelRauber** [Bounceapp/render-action#109]
Hi there!

Does this action work if you have 2-Factor enabled for the account?

I tried it, but it can not login. I also tried using an API key as password, but I still do not have success.

Is this not supported yet?

**Comment by lennartschoch** [comment]
Hey @ManuelRauber!
Sorry, this is unfortunately not supported at the moment.
We're using the `signIn` mutation of Render's GraphQL API to authenticate (which only takes email and password as variables). To use an API key, you'd probably have to provide it as a header.
I would really like to support this, but I am not sure if we'll have time to work on it anytime soon.
In case you want to create a pull request that adds this functionality, it would be highly appreciated though!

**Comment by gjsduarte** [comment]
Hi @ManuelRauber, API authentication is now supported. See PR #136
