### ISSUE TITLE
GraphQL fails with Unauthorized error

### ISSUE THREAD

**Issue by berkes** [Bounceapp/render-action#72]
Render.com only has published documentation for their REST API, so I'm probably lacking information.

This REST API uses a pre-generated Bearer token, and has no reference to Sign In. Yet this action here uses GraphQL to sign in. 
The sign-in works, because when I provide a wrong RENDER_PASSWORD, it fails on sign in. When providing the right one, it fails during `Listing deployments for ***...` with

```
Error: Unauthorized: {"response":{"errors":[{"message":"Unauthorized","extensions":{"code":401}}],"data":null,"status":200},"request":{"query":"query Deploys($serverId: String!) {\n  deploys(serverId: $serverId) {\n    id\n    status\n    branch\n    commitId\n    server {\n      id\n      name\n    }\n  }\n}\n","variables":{"serverId":"***"}}}
```

I'm unsure how to debug whether or not the action adds the correct Bearer token to the headers. And I'm unsure how the GraphQL API is supposed to work as Render seems to have no documentation on it (is it maybe deprecated?)

**Comment by gjsduarte** [comment]
Looking at your description of the problem, the only thing that comes to mind is that the user you're passing doesn't have access to the specified `service-id`.
Have you checked that?
Also are you passing the `service-id` in the form of `srv-XXXXXXXXXXXXXXXXXXXX`?

**Comment by berkes** [comment]
I've now rewritten the CI to just call "raw" CURL commands, instead of using this addon. So I'm no longer using this, and setting it up would require me to not only rewrite our CI, it would endanger our pipeline and even potentially our staging and production env. 

In short: I'm no longer able to check what went wrong. Sorry!
